#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               32
spacebar -m config title                off
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         14
spacebar -m config padding_right        25
spacebar -m config spacing_left         12
spacebar -m config spacing_right        20
spacebar -m config text_font            "Hack Nerd Font:Regular:12.0"
spacebar -m config icon_font            "Hack Nerd Font:Regular:10.0"
spacebar -m config background_color     0x00808080
spacebar -m config foreground_color     0xffEEEEEE
spacebar -m config space_icon_color     0xff000000
spacebar -m config power_icon_color     0xffEEEEEE
spacebar -m config battery_icon_color   0xffEEEEEE
spacebar -m config dnd_icon_color       0xffEEEEEE
spacebar -m config clock_icon_color     0xffEEEEEE
spacebar -m config power_icon_strip      
#spacebar -m config space_icon_strip     • •• ••• •••• •••• ••••• 
spacebar -m config space_icon_strip     1 2 3 4 5 6 7 8 9 10 
#spacebar -m config space_icon_strip     l ll lll llll 
spacebar -m config spaces_for_all_displays  on
spacebar -m config display_seperator    off
spacebar -m config display_separator_icon   ""
spacebar -m config space_icon           ⚡
spacebar -m config power_icon           ⚡
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%A %B %d, %Y %R"
spacebar -m config right_shell          off
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "whoami"

echo "spacebar configuration loaded.."
